default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "comments_notifications_app_development" } %>

test:
  <<: *default
  database: comments_notifications_app_test

production:
  <<: *default
  database: comments_notifications_app_production
  username: comments_notifications_app
  password: <%= ENV["COMMENTS_NOTIFICATIONS_APP_DATABASE_PASSWORD"] %>
